
const appArray = [
    {
        icon: require('../../../assets/vymo.png'),
        appName: 'VYMO',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.getvymo.android',
        iosId: ''
    }, {
        icon: require('../../../assets/m_shell.png'),
        appName: 'MSell',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.enparadigm.bharthiaxa',
        iosId: 'm-sell/id1518565564'
    }, {
        icon: require('../../../assets/i-WIN.png'),
        appName: 'i-Win',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.xoxoday.compass',
        iosId: 'compass-xoxo/id1504258298'
    }, {
        icon: require('../../../assets/i-WIN.png'),
        appName: 'i-Win',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.xoxoday.compassuat',
        iosId: 'compass-xoxo/id1504258298'
    }, {
        icon: require('../../../assets/i-LEARN.png'),
        appName: 'i-Learn',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.chaptervitamins.bharatiaxa',
        iosId: ''
    }, {
        icon: require('../../../assets/i-LEARN.png'),
        appName: 'i-Learn',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.chaptervitamins.bhartiaxa',
        iosId: ''
    }, {
        icon: require('../../../assets/i-EARN.png'),
        appName: 'i-Earn',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.bhartiaxa.mlife',
        iosId: 'm-life/id1550263609'
    }, {
        icon: require('../../../assets/i-RECRUIT.png'),
        appName: 'i-Recruit',
        version: 0,
        mVersion: 0,
        isFetching: false,
        isExists: false,
        isInstalled: false,
        isLatest: false,
        lastUpdated: 1,
        packageName: 'com.bhartiaxa.recruit',
        iosId: ''
    }
]

export default appArray;
