export const ADDCONTACT_REQUEST = 'AddContact/ADDCONTACT_REQUEST';
export const ADDCONTACT_SUCCESS = 'AddContact/ADDCONTACT_SUCCESS';
export const ADDCONTACT_FAILURE = 'AddContact/ADDCONTACT_FAILURE';
