export const DELETECONTACT_REQUEST = 'DeleteContact/DELETECONTACT_REQUEST';
export const DELETECONTACT_SUCCESS = 'DeleteContact/DELETECONTACT_SUCCESS';
export const DELETECONTACT_FAILURE = 'DeleteContact/DELETECONTACT_FAILURE';
